language: node_js
node_js:
  - "node"
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install:
  - cd ./website && yarn install && yarn build && cd ..
script:
  - 
deploy:
  skip_cleanup: true
  provider: firebase
  token:
      secure: "{FIRE_SECRET_KEY}"
  project: "rs-doc"